In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews.csv"

df = pd.read_csv(url)

df.head()

,package_name,review,polarity
0,com.facebook.katana,privacy at least put some option appear offli...,0
1,com.facebook.katana,"messenger issues ever since the last update, ...",0
2,com.facebook.katana,profile any time my wife or anybody has more ...,0
3,com.facebook.katana,the new features suck for those of us who don...,0
4,com.facebook.katana,forced reload on uploading pic on replying co...,0

In [4]:
df.info()
df.describe()
df["polarity"].value_counts()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   package_name  891 non-null    str
 1   review        891 non-null    str
 2   polarity      891 non-null    int64
dtypes: int64(1), str(2)
memory usage: 21.0 KB

polarity
0    584
1    307
Name: count, dtype: int64

In [37]:
df = df.drop(columns=["package_name"], errors="ignore")

df.head()

                                              review  polarity
0  privacy at least put some option appear offlin...         0
1  messenger issues ever since the last update, i...         0
2  profile any time my wife or anybody has more t...         0
3  the new features suck for those of us who don'...         0
4  forced reload on uploading pic on replying com...         0

In [22]:
df["review"] = df["review"].str.strip().str.lower()

df = df.dropna()

In [24]:
from sklearn.model_selection import train_test_split

X = df["review"]
y = df["polarity"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

vec_model = CountVectorizer(stop_words="english")

X_train_vec = vec_model.fit_transform(X_train).toarray()
X_test_vec = vec_model.transform(X_test).toarray()

In [26]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

mnb = MultinomialNB()

mnb.fit(X_train_vec, y_train)

pred_mnb = mnb.predict(X_test_vec)

print("MultinomialNB Accuracy:", accuracy_score(y_test, pred_mnb))

MultinomialNB Accuracy: 0.8156424581005587

In [35]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train_vec, y_train)

pred_gnb = gnb.predict(X_test_vec)

print("GaussianNB Accuracy:", accuracy_score(y_test, pred_gnb))

GaussianNB Accuracy: 0.8044692737430168

In [34]:
from sklearn.naive_bayes import BernoulliNB

bnb = BernoulliNB()

bnb.fit(X_train_vec, y_train)

pred_bnb = bnb.predict(X_test_vec)

print("BernoulliNB Accuracy:", accuracy_score(y_test, pred_bnb))

BernoulliNB Accuracy: 0.770949720670391

In [ ]:
#model comparison
print("MultinomialNB:", accuracy_score(y_test, pred_mnb))
print("GaussianNB:", accuracy_score(y_test, pred_gnb))
print("BernoulliNB:", accuracy_score(y_test, pred_bnb))

MultinomialNB: 0.8156424581005587
GaussianNB: 0.8044692737430168
BernoulliNB: 0.770949720670391

In [32]:
#RandomforestOptomiation
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train_vec, y_train)

rf_pred = rf_model.predict(X_test_vec)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))

Random Forest Accuracy: 0.8156424581005587

In [31]:
#savedmodel
import os
from pickle import dump

os.makedirs("../models", exist_ok=True)

dump(mnb, open("../models/naive_bayes_model.sav", "wb"))

In [30]:
#LogisticRegressionModl
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train_vec, y_train)

lr_pred = lr_model.predict(X_test_vec)

print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))

Logistic Regression Accuracy: 0.8324022346368715

In [29]:
#supportvectormachine
from sklearn.svm import LinearSVC

svm_model = LinearSVC()

svm_model.fit(X_train_vec, y_train)

svm_pred = svm_model.predict(X_test_vec)

print("SVM Accuracy:", accuracy_score(y_test, svm_pred))

SVM Accuracy: 0.8324022346368715